module.exports ={
    style_ChuanQi:{
        childStyles:[
            {
                style:"红蓝血条类型",
                zorder:["bg","prop"],
                relpath:{
                    bg:"bg/style_Blood",
                    prop:"prop/style_Blood"
                }
            },
            {
                style:"早期通用icon1",
                zorder:["bg","prop","effect"],
                relpath:{
                    bg:"bg/style_Common",
                    prop:"prop/style_Common/style_Time1",
                    effect:"effect/effect_top/"
                }
            },
            {
                style:"早期通用icon1",
                zorder:["bg","effect","prop"],
                relpath:{
                    bg:"bg/style_Common",
                    prop:"prop/style_Common/style_Time1",
                    effect:"effect/effect_mid/"
                }
            },
            {
                style:"二期通用icon",
                zorder:["bg","prop"],
                relpath:{
                    bg:"bg/style_Common",
                    prop:"prop/style_Common/style_Time2"
                }
            },
            {
                style:"圆形框icon",
                zorder:["bg","prop","frame"],
                relpath:{
                    bg:"bg/style_Common",
                    prop:"prop/style_Circle/",
                    frame:"prop/style_Circle/"
                }
            },
            {
                style:"方形框icon",
                zorder:["bg","prop","frame"],
                relpath:{
                    bg:"bg/style_Common",
                    prop:"prop/style_Square/",
                    frame:"prop/style_Square/"
                }
            }
        ]
    },
    style_SanGuo:{
        childStyles:[
            {
                style:"蓝色体系icon",
                zorder:["bg","prop"],
                relpath:{
                    bg:"bg/style_Blue/",
                    prop:"prop/style_Blue/",
                }
            },
            {
                style:"通用icon",
                zorder:["bg","prop"],
                relpath:{
                    bg:"bg/style_Normal/",
                    prop:"prop/style_Normal/",
                }
            },
        ]
    },
    style_DiZhu:{
        zorder:["bg","prop","effect","subscript"]
    },
    style_Fruit:{
        zorder:["bg","prop","subscript"]
    },
    style_QSanGuo:{
        zorder:["bg","prop","effect"]
    },
    style_Poker:{
        zorder:["bg","prop","subscript"]
    },
    style_Girl:{
        zorder:["bg","prop","subscript"]
    },
    style_NiuNiu:{
        zorder:["bg","prop","subscript"]
    }
 
}